name: Uxtron bug report
description: Use this if a bug has been found in the Uxtron bot
labels: ["bug"]
body:
  - type: markdown
    value: "## Uxtron bug/typo report"
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug! If you need real-time help, please join our discord server: https://discord.gg/EuzUKcNuKD
body:
  - type: dropdown
    attributes:
      label: What type of bug is this?
      description: Please select the type of bug you are reporting
      options: 
        - Typo
        - not responding
  - type: markdown
    attributes:
      value: "Before you open a new report, please check if a similar report already exists here: github.com/Uxtron-team/Uxtron-bot-docs/issues"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and consise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How is the error experienced/how to experience the bug
      description: How do you experience the bug? Please provide a clear description.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Provide a screenshot and/or video as proof of the bug
    validations:
      required: true
  - type: textarea
    id: discordid
    attributes:
      label: Discord username and tag
      description: Please provide your discord username and tag so we can contact you if needed. This is optional but it will allow us to contact you with any information.
    validations:
      required: false
     
