name: Uxtron bug report
description: Use this if a bug has been found in the Uxtron bot
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this report is not a duplicate of an already existing report. If you need real-time help, join us on Discord.
  - type: dropdown
    attributes:
      label: What type of bug is this?
      description: Please select the type of bug you are reporting
      options: 
        - The bot not responding
        - The bot responding incorrectly
        - The bot not acting correctly
        - Other
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and consise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How is the error experienced/how to experience the bug
      description: How do you experience the bug? Please provide a clear description.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Provide a screenshot and/or video as proof of the bug
    validations:
      required: true
  - type: checkboxes
    id: agreement
    attributes:
      label: Agreements
      description: Please agree to the following before you submit this report
      options:
        - label: I agree that you have used the bot normally and have not purposely made a fake error message
          required: true
        - label: I agree that this report is not a duplicate of another report
          required: true
     
