name: Uxtron bug report
description: Use this if a bug has been found in the Uxtron bot
labels: ["bug"]
body:
  - type: markdown
  value: "###### Thank you for taking your time to help report this bug! Your help is appreciated."
  - type: markdown
  value: "@hi-there-child | @King-click | @DecodedFinn | @Creepermonst"
  - type: dropdown
    attributes:
      label: In what ways is the bot malfunctioning?
      description: Please select the category of the issue you are reporting. If your issue isn't listed below, please try to select the closest match to your issue, or choose the "other" option.
      options: 
        - The bot is not responding
        - The bot is responding incorrectly
        - The bot is not acting correctly
        - Command argument errors
        - [GENERAL] Command errors
        - [GENERAL] Embed errors
        - [GENERAL] Feature errors
        - Other
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: other - error type
      description: If you chose 'other' for the error type (above), please specify the error here.
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear description of what the error is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How can you reproduce this bug?
      description: Please give a step by step guide on how to reproduce this bug or mistake. It would be greatly appreciated if you could go into detail with each step!
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Provide a screenshot and/or video as proof of the bug.
    validations:
      required: true
  - type: checkboxes
    id: agreement
    attributes:
      label: Agreements
      description: Please agree to the following statements before you submit this report.
      options:
        - label: The issue listed in this report was experienced while using the bot under normal circumstances.
          required: true
        - label: I have at least put some effort into making sure this issue has not been previously reported by another user.
          required: true
        - label: I acknowledge that once I submit this report, I give all admins and moderators permission to publicize this report, with all details included, and with my username publicly visible.
          required: true
        - label: I am confident that this report is genuine and is an actual error in the bot, and have adequately described the issue so the admins have enough information to reproduce this error and fix it.
          required: true
     
