blank_issues_enabled: false
contact_links:
  - name: Feature requests and the community forum
    url: https://github.com/Uxtron-team/Uxtron-bot-docs/discussions
    about: Need some help or want to request a feature? Head over to our forum!
  - name: Uxtron bot wiki
    url: https://github.com/Uxtron-team/Uxtron-bot-docs/wiki
    about: A link to the Uxtron bot wiki
  - name: Uxtron bot documentation
    url: https://github.com/Uxtron-team/Uxtron-bot-docs/tree/main/docs
    about: Want more detailed explanations on how to use the Uxtron bot? Come here!
  - name: Uxtron support server
    url: https://discord.gg/EuzUKcNuKD
    about: Do you need real-time support? Head over here to our support server!
