name: Tutorial request
description: Request a tutorial
labels: ["tutorial request"]
body:
  - type: dropdown
    id: type
    attributes:
      label: What type of tutorial are you requesting
      options:
        - Feature usage tutorials
        - Setting up tutorials
        - Command usage tutorials
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear description on what the tutorial is for. 
    validations:
      required: true
  - type: textarea
    id: aim
    attributes:
      label: Tutorial aim
      description: Provide a clear description on what the tutorial will teach.
    validations:
      required: true
  - type: checkbox
    id: agreements
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I agree that this tutorial request is related to Uxtron
        required: true
        - label: I agree that this tutorial request is appropriate
        required: true
        - label: I agree that this tutorial cannot be found on the official Uxtron bot wiki
        required: true
